using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace E_Word_Api.Migrations
{
    /// <inheritdoc />
    public partial class WordPrimaryKeyAutoGenerated : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "e2566882-b466-41f5-84f7-7cadc65fd9e4");

            migrationBuilder.DeleteData(
                table: "AspNetUserRoles",
                keyColumns: new[] { "RoleId", "UserId" },
                keyValues: new object[] { "7322dd9c-1e86-46c1-a006-d3b832b2ddb8", "e89f1ca1-b582-4307-a709-142eaf357974" });

            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "7322dd9c-1e86-46c1-a006-d3b832b2ddb8");

            migrationBuilder.DeleteData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "e89f1ca1-b582-4307-a709-142eaf357974");

            migrationBuilder.InsertData(
                table: "AspNetRoles",
                columns: new[] { "Id", "ConcurrencyStamp", "Name", "NormalizedName" },
                values: new object[,]
                {
                    { "b821b8bf-0525-4d16-8cb6-f0e05d4af2bc", null, "Admin", "ADMIN" },
                    { "fa97a676-ff29-48dc-9c5f-6d8be12c97d2", null, "User", "USER" }
                });

            migrationBuilder.InsertData(
                table: "AspNetUsers",
                columns: new[] { "Id", "AccessFailedCount", "Avatar", "City", "ConcurrencyStamp", "CreatedAt", "Email", "EmailConfirmed", "LockoutEnabled", "LockoutEnd", "NickName", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled", "UserName" },
                values: new object[] { "60d4da50-0e62-4999-8714-758d3ac5e290", 0, null, "北京市", "851aad6f-93e9-44cc-814a-1c03d5c73619", new DateTime(2026, 5, 3, 6, 52, 29, 226, DateTimeKind.Utc).AddTicks(360), "admin@eword.com", false, true, null, "Admin", "ADMIN@EWORD.COM", "ADMIN@EWORD.COM", "AQAAAAIAAYagAAAAELJKXkUD5tHmfTNcRJ+F4w8PzVgoP8wL9O8Zyh/g/ZzpvzFPL2yItCvn21UKUmPq/g==", "17323895436", false, "3efa7b6a-a229-4bd8-87e8-0cb01fbdc7b6", false, "admin@eword.com" });

            migrationBuilder.InsertData(
                table: "AspNetUserRoles",
                columns: new[] { "RoleId", "UserId" },
                values: new object[] { "b821b8bf-0525-4d16-8cb6-f0e05d4af2bc", "60d4da50-0e62-4999-8714-758d3ac5e290" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "fa97a676-ff29-48dc-9c5f-6d8be12c97d2");

            migrationBuilder.DeleteData(
                table: "AspNetUserRoles",
                keyColumns: new[] { "RoleId", "UserId" },
                keyValues: new object[] { "b821b8bf-0525-4d16-8cb6-f0e05d4af2bc", "60d4da50-0e62-4999-8714-758d3ac5e290" });

            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "b821b8bf-0525-4d16-8cb6-f0e05d4af2bc");

            migrationBuilder.DeleteData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "60d4da50-0e62-4999-8714-758d3ac5e290");

            migrationBuilder.InsertData(
                table: "AspNetRoles",
                columns: new[] { "Id", "ConcurrencyStamp", "Name", "NormalizedName" },
                values: new object[,]
                {
                    { "7322dd9c-1e86-46c1-a006-d3b832b2ddb8", null, "Admin", "ADMIN" },
                    { "e2566882-b466-41f5-84f7-7cadc65fd9e4", null, "User", "USER" }
                });

            migrationBuilder.InsertData(
                table: "AspNetUsers",
                columns: new[] { "Id", "AccessFailedCount", "Avatar", "City", "ConcurrencyStamp", "CreatedAt", "Email", "EmailConfirmed", "LockoutEnabled", "LockoutEnd", "NickName", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled", "UserName" },
                values: new object[] { "e89f1ca1-b582-4307-a709-142eaf357974", 0, null, "北京市", "3afdbaba-e47c-410c-a516-7fe45dbc7c96", new DateTime(2026, 5, 3, 6, 24, 12, 538, DateTimeKind.Utc).AddTicks(6956), "admin@eword.com", false, true, null, "Admin", "ADMIN@EWORD.COM", "ADMIN@EWORD.COM", "AQAAAAIAAYagAAAAEA30BqRLt1WhvQA0azCCVKBv3lXCRXQgWRn158ze/YqLW8IHefuPRk3lJnVCawqkfQ==", "17323895436", false, "bfb71af8-326b-4694-815f-8839271f00f6", false, "admin@eword.com" });

            migrationBuilder.InsertData(
                table: "AspNetUserRoles",
                columns: new[] { "RoleId", "UserId" },
                values: new object[] { "7322dd9c-1e86-46c1-a006-d3b832b2ddb8", "e89f1ca1-b582-4307-a709-142eaf357974" });
        }
    }
}
